src/HarborLight.WebUI/Controllers/PageController.cs
using Microsoft.AspNetCore.Mvc;

namespace HarborLight.WebUI.Controllers
{
    public class PageController : Controller
    {
        public IActionResult Chat() => View();
        public IActionResult Confirmation() => View();
        public IActionResult Contacts() => View();
        public IActionResult Error() => View();
        public IActionResult Error404() => View();
        public IActionResult ErrorAnnounced() => View();
        public IActionResult Forget() => View();
        public IActionResult ForumDiscussion() => View();
        public IActionResult ForumList() => View();
        public IActionResult ForumThreads() => View();
        public IActionResult InboxGeneral() => View();
        public IActionResult InboxRead() => View();
        public IActionResult InboxWrite() => View();
        public IActionResult Invoice() => View();
        public IActionResult Locked() => View();
        public IActionResult Login() => View();
        public IActionResult LoginAlt() => View();
        public IActionResult Profile() => View();
        public IActionResult Projects() => View();
        public IActionResult Register() => View();
        public IActionResult Search() => View();
    }
}

src/HarborLight.WebUI/Views/Shared/_Compose.cshtml
<div id="panel-compose" class="panel w-100 position-fixed pos-bottom pos-right mb-0 z-index-cloud mr-lg-4 shadow-3 border-bottom-left-radius-0 border-bottom-right-radius-0 expand-full-height-on-mobile expand-full-width-on-mobile shadow" style="max-width:40rem; height:35rem; display: none;">
	<div class="position-relative h-100 w-100 d-flex flex-column">
		<div class="panel-hdr bg-fusion-600 height-4 d-none d-sm-none d-lg-flex">
			<h4 class="flex-1 fs-lg color-white mb-0 pl-3">
				New Message
			</h4>
			<div class="panel-toolbar pr-2">
				<a href="javascript:void(0);" class="btn btn-icon btn-icon-light fs-xl mr-1" data-action="panel-fullscreen" data-toggle="tooltip" data-offset="0,10" data-original-title="Fullscreen" data-placement="bottom">
					<i class="@(Settings.Theme.IconPrefix) fa-expand-alt"></i>
				</a>
				<a href="javascript:void(0);" class="btn btn-icon btn-icon-light fs-xl" data-action="toggle" data-class="d-flex" data-target="#panel-compose" data-toggle="tooltip" data-original-title="Save & Close" data-placement="bottom">
					<i class="@(Settings.Theme.IconPrefix) fa-times"></i>
				</a>
			</div>
		</div>
		<div class="d-flex d-lg-none align-items-center px-3 py-3 bg-faded  border-faded border-top-0 border-left-0 border-right-0 flex-shrink-0">
			<h3 class="subheader-title">
				New message
			</h3>
			<div class="ml-auto">
				<button type="button" class="btn btn-outline-danger" data-action="toggle" data-class="d-flex" data-target="#panel-compose">Cancel</button>
			</div>
		</div>
		<div class="panel-container show rounded-0 flex-1 d-flex flex-column">
			<partial name="_ComposeLayout"/>
		</div>
	</div>
</div>

src/HarborLight.WebUI/Views/Shared/_DropdownApp.cshtml
<div class="dropdown-header bg-trans-gradient d-flex justify-content-center align-items-center rounded-top">
	<h4 class="m-0 text-center color-white">
		Quick Shortcut
		<small class="mb-0 opacity-80">User Applications & Addons</small>
	</h4>
</div>
<div class="custom-scroll h-100">
	<ul class="app-list">
		<li>
			<a href="#" class="app-list-item hover-white">
				<span class="icon-stack">
					<i class="base-2 icon-stack-3x color-primary-600"></i>
					<i class="base-3 icon-stack-2x color-primary-700"></i>
					<i class="ni ni-settings icon-stack-1x text-white fs-lg"></i>
				</span>
				<span class="app-list-name">
					Services
				</span>
			</a>
		</li>
		<li>
			<a href="#" class="app-list-item hover-white">
				<span class="icon-stack">
					<i class="base-2 icon-stack-3x color-primary-400"></i>
					<i class="base-10 text-white icon-stack-1x"></i>
					<i class="ni md-profile color-primary-800 icon-stack-2x"></i>
				</span>
				<span class="app-list-name">
					Account
				</span>
			</a>
		</li>
		<li>
			<a href="#" class="app-list-item hover-white">
				<span class="icon-stack">
					<i class="base-9 icon-stack-3x color-success-400"></i>
					<i class="base-2 icon-stack-2x color-success-500"></i>
					<i class="ni ni-shield icon-stack-1x text-white"></i>
				</span>
				<span class="app-list-name">
					Security
				</span>
			</a>
		</li>
		<li>
			<a href="#" class="app-list-item hover-white">
				<span class="icon-stack">
					<i class="base-18 icon-stack-3x color-info-700"></i>
					<span class="position-absolute pos-top pos-left pos-right color-white fs-md mt-2 fw-400">28</span>
				</span>
				<span class="app-list-name">
					Calendar
				</span>
			</a>
		</li>
		<li>
			<a href="#" class="app-list-item hover-white">
				<span class="icon-stack">
					<i class="base-7 icon-stack-3x color-info-500"></i>
					<i class="base-7 icon-stack-2x color-info-700"></i>
					<i class="ni ni-graph icon-stack-1x text-white"></i>
				</span>
				<span class="app-list-name">
					Stats
				</span>
			</a>
		</li>
		<li>
			<a href="#" class="app-list-item hover-white">
				<span class="icon-stack">
					<i class="base-4 icon-stack-3x color-danger-500"></i>
					<i class="base-4 icon-stack-1x color-danger-400"></i>
					<i class="ni ni-envelope icon-stack-1x text-white"></i>
				</span>
				<span class="app-list-name">
					Messages
				</span>
			</a>
		</li>
		<li>
			<a href="#" class="app-list-item hover-white">
				<span class="icon-stack">
					<i class="base-4 icon-stack-3x color-fusion-400"></i>
					<i class="base-5 icon-stack-2x color-fusion-200"></i>
					<i class="base-5 icon-stack-1x color-fusion-100"></i>
					<i class="@(Settings.Theme.IconPrefix) fa-keyboard icon-stack-1x color-info-50"></i>
				</span>
				<span class="app-list-name">
					Notes
				</span>
			</a>
		</li>
		<li>
			<a href="#" class="app-list-item hover-white">
				<span class="icon-stack">
					<i class="base-16 icon-stack-3x color-fusion-500"></i>
					<i class="base-10 icon-stack-1x color-primary-50 opacity-30"></i>
					<i class="base-10 icon-stack-1x fs-xl color-primary-50 opacity-20"></i>
					<i class="@(Settings.Theme.IconPrefix) fa-dot-circle icon-stack-1x text-white opacity-85"></i>
				</span>
				<span class="app-list-name">
					Photos
				</span>
			</a>
		</li>
		<li>
			<a href="#" class="app-list-item hover-white">
				<span class="icon-stack">
					<i class="base-19 icon-stack-3x color-primary-400"></i>
					<i class="base-7 icon-stack-2x color-primary-300"></i>
					<i class="base-7 icon-stack-1x fs-xxl color-primary-200"></i>
					<i class="base-7 icon-stack-1x color-primary-500"></i>
					<i class="@(Settings.Theme.IconPrefix) fa-globe icon-stack-1x text-white opacity-85"></i>
				</span>
				<span class="app-list-name">
					Maps
				</span>
			</a>
		</li>
		<li>
			<a href="#" class="app-list-item hover-white">
				<span class="icon-stack">
					<i class="base-5 icon-stack-3x color-success-700 opacity-80"></i>
					<i class="base-12 icon-stack-2x color-success-700 opacity-30"></i>
					<i class="@(Settings.Theme.IconPrefix) fa-comment-alt icon-stack-1x text-white"></i>
				</span>
				<span class="app-list-name">
					Chat
				</span>
			</a>
		</li>
		<li>
			<a href="#" class="app-list-item hover-white">
				<span class="icon-stack">
					<i class="base-5 icon-stack-3x color-warning-600"></i>
					<i class="base-7 icon-stack-2x color-warning-800 opacity-50"></i>
					<i class="@(Settings.Theme.IconPrefix) fa-phone icon-stack-1x text-white"></i>
				</span>
				<span class="app-list-name">
					Phone
				</span>
			</a>
		</li>
		<li>
			<a href="#" class="app-list-item hover-white">
				<span class="icon-stack">
					<i class="base-6 icon-stack-3x color-danger-600"></i>
					<i class="@(Settings.Theme.IconPrefix) fa-chart-line icon-stack-1x text-white"></i>
				</span>
				<span class="app-list-name">
					Projects
				</span>
			</a>
		</li>
		<li class="w-100">
			<a href="#" class="btn btn-default mt-4 mb-2 pr-5 pl-5"> Add more apps </a>
		</li>	
	</ul>	
</div>

src/HarborLight.WebUI/Views/Shared/_Favicon.cshtml
<link rel="apple-touch-icon" sizes="180x180" href="~/img/favicon/apple-touch-icon.png">
<link rel="icon" type="image/png" sizes="32x32" href="~/img/favicon/favicon-32x32.png">
<link rel="mask-icon" href="~/img/favicon/safari-pinned-tab.svg" color="#5bbad5">

src/HarborLight.WebUI/Views/Shared/_GoogleAnalytics.cshtml
@if (Settings.Features.GoogleAnalytics)
{
	<script>
	  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
	  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
	  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
	  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
	  ga('create', '@ViewBag.GoogleAnalytics', 'auto');
	  ga('send', 'pageview');
	</script>
}

src/HarborLight.WebUI/Views/Shared/_Head.cshtml
<meta charset="utf-8">
<title>
@if (ViewBag.Title?.Length > 0)
{
	<text>@ViewData["Title"] - @ViewData["Category1"] - @Settings.App v@(Settings.Version)</text>
} else {
	@Settings.App
}
</title>
<base href="~/"/>
<meta name="description" content="@ViewBag.Title">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no, user-scalable=no, minimal-ui">
<meta name="apple-mobile-web-app-capable" content="yes" />
<meta name="msapplication-tap-highlight" content="no">
<link id="vendorsbundle" rel="stylesheet" media="screen, print" href="~/css/vendors.bundle.css">
<link id="appbundle" rel="stylesheet" media="screen, print" href="~/css/app.bundle.css">
<link id="mytheme" rel="stylesheet" media="screen, print" href="~/css/themes/cust-theme-3.css">
<link id="myskin" rel="stylesheet" media="screen, print" href="~/css/skins/skin-master.css">
<link rel="stylesheet" media="screen, print" href="~/css/site.css">
<partial name="_Favicon"/>

src/HarborLight.WebUI/Views/Shared/_Menu.cshtml
<div id="js-inbox-menu" class="flex-wrap position-relative bg-white slide-on-mobile slide-on-mobile-left">
	<div class="position-absolute pos-top pos-bottom w-100">
		<div class="d-flex h-100 flex-column">
			<div class="px-3 px-sm-4 px-lg-5 py-4 align-items-center">
				<div class="btn-group btn-block" role="group" aria-label="Button group with nested dropdown ">
					<button type="button" class="btn btn-danger btn-block fs-md" data-action="toggle" data-class="d-flex" data-target="#panel-compose" data-focus="message-to">Compose</button>
					<div class="btn-group" role="group">
						<button id="btnGroupDrop1" type="button" class="btn btn-danger dropdown-toggle px-2 js-waves-off" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></button>
						<div class="dropdown-menu p-0" aria-labelledby="btnGroupDrop1">
							<a class="dropdown-item" href="#">Work group A</a>
							<a class="dropdown-item" href="#">New page</a>
							<a class="dropdown-item" href="#">Edit signature</a>
							<div class="dropdown-divider m-0"></div>
							<a class="dropdown-item" href="#"> <i class="fas fa-plus width-1"></i> Add more</a>
						</div>
					</div>
				</div>
			</div>
			<div class="flex-1 pr-3">
				<a href="/page/inboxgeneral" class="dropdown-item px-3 px-sm-4 pr-lg-3 pl-lg-5 py-2 fs-md font-weight-bold d-flex justify-content-between rounded-pill border-top-left-radius-0 border-bottom-left-radius-0 @(ViewBag.PageName == "page_inbox_general" ? "active" : "")">
					<div>
						<i class="fas fa-folder-open width-1"></i>Inbox
					</div>
					<div class="fw-400 fs-xs js-unread-emails-count"></div>
				</a>
				<a href="javascript:void(0)" class="dropdown-item px-3 px-sm-4 pr-lg-3 pl-lg-5 py-2 fs-md d-flex justify-content-between rounded-pill border-top-left-radius-0 border-bottom-left-radius-0">
					<div>
						<i class="fas fa-star width-1"></i>Starred
					</div>
					<div class="fw-400 fs-xs">(6)</div>
				</a>
				<a href="javascript:void(0)" class="dropdown-item px-3 px-sm-4 pr-lg-3 pl-lg-5 py-2 fs-md d-flex justify-content-between rounded-pill border-top-left-radius-0 border-bottom-left-radius-0">
					<div>
						<i class="fas fa-edit width-1"></i>Draft
					</div>
					<div class="fw-400 fs-xs">(5)</div>
				</a>
				<a href="javascript:void(0)" class="dropdown-item px-3 px-sm-4 pr-lg-3 pl-lg-5 py-2 fs-md d-flex justify-content-between rounded-pill border-top-left-radius-0 border-bottom-left-radius-0">
					<div>
						<i class="fas fa-paper-plane width-1"></i>Sent
					</div>
				</a>
				<a href="javascript:void(0)" class="dropdown-item px-3 px-sm-4 pr-lg-3 pl-lg-5 py-2 fs-md d-flex justify-content-between rounded-pill border-top-left-radius-0 border-bottom-left-radius-0">
					<div>
						<i class="fas fa-exclamation-triangle width-1"></i>Spam
					</div>
				</a>
				<a href="javascript:void(0)" class="dropdown-item px-3 px-sm-4 pr-lg-3 pl-lg-5 py-2 fs-md font-weight-bold d-flex justify-content-between rounded-pill border-top-left-radius-0 border-bottom-left-radius-0">
					<div>
						<i class="fas fa-trash width-1"></i>Trash
					</div>
				</a>
			</div>
			<div class="px-5 py-3 fs-nano fw-500">
				1.5 GB (10%) of 15 GB used
				<div class="progress mt-1" style="height: 7px;">
					<div class="progress-bar" role="progressbar" style="width: 11%;" aria-valuenow="11" aria-valuemin="0" aria-valuemax="100"></div>
				</div>
			</div>
		</div>
	</div>
</div>
<div class="slide-backdrop" data-action="toggle" data-class="slide-on-mobile-left-show" data-target="#js-inbox-menu"></div>

src/HarborLight.WebUI/Views/Shared/_NavFilterMsg.cshtml
<div class="filter-message js-filter-message bg-success-600"></div>

src/HarborLight.WebUI/Views/Shared/_NavFooter.cshtml
<div class="nav-footer shadow-top">
	<a href="#" onclick="return false;" data-action="toggle" data-class="nav-function-minify" class="hidden-md-down">
		<i class="ni ni-chevron-right"></i>
		<i class="ni ni-chevron-right"></i>
	</a>
	<ul class="list-table m-auto nav-footer-buttons">
		<li>
			<a href="javascript:void(0);" data-toggle="tooltip" data-placement="top" title="Chat logs">
				<i class="@(Settings.Theme.IconPrefix) fa-comments"></i>
			</a>
		</li>
		<li>
			<a href="javascript:void(0);" data-toggle="tooltip" data-placement="top" title="Support Chat">
				<i class="@(Settings.Theme.IconPrefix) fa-life-ring"></i>
			</a>
		</li>
		<li>
			<a href="javascript:void(0);" data-toggle="tooltip" data-placement="top" title="Make a call">
				<i class="@(Settings.Theme.IconPrefix) fa-phone"></i>
			</a>
		</li>
	</ul>
</div>

src/HarborLight.WebUI/Views/Shared/_PageFooter.cshtml
@if (Settings.Features.AppFooter)
{
<footer class="page-footer" role="contentinfo">
	<div class="d-flex align-items-center flex-1 text-muted">
		<span class="hidden-md-down fw-700">2020 &copy; @Settings.App for @Settings.AppFlavor by&nbsp;<a href="https://wrapbootstrap.com/theme/HarborLight-asp.net-core-responsive-webapp-WB073L89G?ref=Walapa" class="text-primary fw-500" title="Walapa" target="_blank">Walapa</a></span>
	</div>
	<div>
		<ul class="list-table m-0">
			<li><a href="/intel/introduction" class="text-secondary fw-700">About</a></li>
			<li class="pl-3"><a href="/info/applicensing" class="text-secondary fw-700">License</a></li>
			<li class="pl-3"><a href="/info/appdocs" class="text-secondary fw-700">Documentation</a></li>
			<li class="pl-3 fs-xl"><a href="https://wrapbootstrap.com/user/Walapa" class="text-secondary" target="_blank"><i class="@(Settings.Theme.IconPrefix) fa-question-circle" aria-hidden="true"></i></a></li>
		</ul>
	</div>
</footer>
}

src/HarborLight.WebUI/Views/Shared/_PageHeader.cshtml
@if (Settings.Features.AppHeader)
{
<header class="page-header" role="banner">
	<partial name="_Logo"/>
	@if (Settings.Features.AppLayoutShortcut)
{
	<div class="hidden-md-down dropdown-icon-menu position-relative">
		<a href="#" class="header-btn btn js-waves-off" data-action="toggle" data-class="nav-function-hidden" title="Hide Navigation">
			<i class="ni ni-menu"></i>
		</a>
		<ul>
			<li>
				<a href="#" class="btn js-waves-off" data-action="toggle" data-class="nav-function-minify" title="Minify Navigation">
					<i class="ni ni-minify-nav"></i>
				</a>
			</li>
			<li>
				<a href="#" class="btn js-waves-off" data-action="toggle" data-class="nav-function-fixed" title="Lock Navigation">
					<i class="ni ni-lock-nav"></i>
				</a>
			</li>
		</ul>
	</div>
	}
	<div class="hidden-lg-up">
		<a href="#" class="header-btn btn press-scale-down" data-action="toggle" data-class="mobile-nav-on">
			<i class="ni ni-menu"></i>
		</a>
	</div>
	<div class="search">
		<form class="app-forms hidden-xs-down" role="search" asp-controller="Page" asp-action="Search" autocomplete="off">
			<input type="text" id="search-field" placeholder="Search for anything" class="form-control" tabindex="1">
			<a href="#" onclick="return false;" class="btn-danger btn-search-close js-waves-off d-none" data-action="toggle" data-class="mobile-search-on">
				<i class="@(Settings.Theme.IconPrefix) fa-times"></i>
			</a>
		</form>
	</div>
	<div class="ml-auto d-flex">
		<div class="hidden-sm-up">
			<a href="#" class="header-icon" data-action="toggle" data-class="mobile-search-on" data-focus="search-field" title="Search">
				<i class="@(Settings.Theme.IconPrefix) fa-search"></i>
			</a>
		</div>
		@if (Settings.Features.LayoutSettings)
{
		<div class="hidden-md-down">
			<a href="#" class="header-icon" data-toggle="modal" data-target=".js-modal-settings">
				<i class="@(Settings.Theme.IconPrefix) fa-cog"></i>
			</a>
		</div>	
		}
		<div>
			<a href="#" class="header-icon" data-toggle="dropdown" title="My Apps">
				<i class="@(Settings.Theme.IconPrefix) fa-cube"></i>
			</a>
			<div class="dropdown-menu dropdown-menu-animated w-auto h-auto">
				<partial name="_DropdownApp"/>
			</div>
		</div>
		@if (Settings.Features.ChatInterface)
{
		<a href="#" class="header-icon" data-toggle="modal" data-target=".js-modal-messenger">
			<i class="@(Settings.Theme.IconPrefix) fa-globe"></i>
			<span class="badge badge-icon">!</span>
		</a>
		}
		<div>
			<a href="#" class="header-icon" data-toggle="dropdown" title="You got 11 notifications">
				<i class="@(Settings.Theme.IconPrefix) fa-bell"></i>
				<span class="badge badge-icon">11</span>
			</a>
			<div class="dropdown-menu dropdown-menu-animated dropdown-xl">
				<partial name="_DropdownNotification"/>
			</div>
		</div>
		<div>
			<a href="#" data-toggle="dropdown" title="@(Settings.Theme.Email)" class="header-icon d-flex align-items-center justify-content-center ml-2">
				<img src="~/img/demo/avatars/@(Settings.Theme.Avatar)" class="profile-image rounded-circle" alt="@(Settings.Theme.User)"> 
			</a>
			<div class="dropdown-menu dropdown-menu-animated dropdown-lg">
				<partial name="_DropdownMenu"/>
			</div>
		</div>
	</div>
</header>
}

src/HarborLight.WebUI/Views/Shared/_ScriptsBasePlugins.cshtml
<script src="~/js/vendors.bundle.js"></script>
<script src="~/js/app.bundle.js"></script>
<script src="~/js/site.js"></script>

src/HarborLight.WebUI/Views/Shared/_ShortcutMessenger.cshtml
@if (Settings.Features.ChatInterface)
{
<div class="modal fade js-modal-messenger modal-backdrop-transparent" tabindex="-1" role="dialog" aria-hidden="true">
   <div class="modal-dialog modal-dialog-right">
	  <div class="modal-content h-100">
		 <div class="dropdown-header bg-trans-gradient d-flex align-items-center w-100">
			<div class="d-flex flex-row align-items-center mt-1 mb-1 color-white">
				<span class="mr-2">
					<span class="rounded-circle profile-image d-block" style="background-image:url('/img/demo/avatars/avatar-d.png'); background-size: cover;"></span>
				</span>
				<div class="info-card-text">
					<a href="javascript:void(0);" class="fs-lg text-truncate text-truncate-lg text-white" data-toggle="dropdown" aria-expanded="false">
						Tracey Chang 
						<i class="@(Settings.Theme.IconPrefix) fa-angle-down d-inline-block ml-1 text-white fs-md"></i>
					</a>
					<div class="dropdown-menu">
						<a class="dropdown-item" href="#">Send Email</a>
						<a class="dropdown-item" href="#">Create Appointment</a>
						<a class="dropdown-item" href="#">Block User</a>
					</div>
					<span class="text-truncate text-truncate-md opacity-80">IT Director</span>
				</div>
			</div>
			<button type="button" class="close text-white position-absolute pos-top pos-right p-2 m-1 mr-2" data-dismiss="modal" aria-label="Close">
				<span aria-hidden="true"><i class="@(Settings.Theme.IconPrefix) fa-times"></i></span>
			</button>
		 </div>
		 <div class="modal-body p-0 h-100 d-flex">
			<partial name="_TabMsgr"/>
		 </div>
	  </div>
   </div>
</div>
}